/* Content and brand configuration live here. Layout code should remain reusable. */
window.SITE={
name:"Artist Playground",tagline:"Where artists play, and audiences discover.",
theme:{colors:{yellow:"#FADF12",blue:"#01ACE0",ink:"#111111",paper:"#FFFFFF",soft:"#F5F5F2"},fonts:{display:"'Josefin Sans', sans-serif",body:"'Nunito Sans', sans-serif"}},
nav:[{label:"About",href:"#about"},{label:"What's On",href:"#updates"},{label:"Productions",href:"#productions"},{label:"For Schools",href:"#schools"},{label:"Acting School",href:"#school"},{label:"Contact",href:"#contact"}],
hero:{eyebrow:"Artist Playground",title:"Where artists play, and audiences discover.",text:"A home for performance, creativity, learning, and the people who bring stories to life.",buttons:[{label:"What's on",href:"#updates",kind:"primary"},{label:"Explore our work",href:"#productions",kind:"secondary"}]},
about:{eyebrow:"Who we are",title:"A playground for artists. A place for audiences.",lead:"Artist Playground is a space for creative work, performance, learning, and discovery.",paragraphs:["We create opportunities for artists to play, explore, experiment, and share their work with audiences.","Our programs and productions bring artists, students, schools, and communities together through performance."],highlights:[{title:"Create",text:"Spaces and opportunities for artists to make work."},{title:"Perform",text:"Productions and performances for audiences."},{title:"Learn",text:"Workshops and learning through the arts."}]},
updates:{eyebrow:"What's on",title:"Latest updates",lead:"Discover upcoming performances, programs, and announcements.",featured:{label:"Featured",day:"—",month:"Coming soon",title:"Upcoming Artist Playground activity",text:"Details about the next performance or program will appear here.",button:"Get in touch",href:"#contact"},news:[{when:"Update",title:"Productions",text:"New performances and projects will be announced here."},{when:"Update",title:"Programs",text:"Workshops, classes, and other programs will appear here."},{when:"Update",title:"Collaborations",text:"Creative collaborations and community activities will be shared here."}]},
productions:{eyebrow:"Our work",title:"Productions",lead:"A growing body of performance work for different audiences and spaces.",plays:[{title:"Production title",by:"Artist Playground",text:"Production information can be added here."},{title:"Production title",by:"Artist Playground",text:"Production information can be added here."},{title:"Production title",by:"Artist Playground",text:"Production information can be added here."},{title:"Production title",by:"Artist Playground",text:"Production information can be added here."}]},
schools:{eyebrow:"For schools",title:"Bring live performance to your students.",lead:"Programs can be adapted for schools, student audiences, and learning environments.",text:"Tell us about your school, audience, preferred program, and schedule. We can discuss the right format for your students.",button:"Start a conversation",points:[{title:"Performance",text:"Bring live work to your school or venue."},{title:"Learning",text:"Connect performance with classroom experiences."},{title:"Partnership",text:"Plan a program around your school's needs."}]},
actingSchool:{eyebrow:"Learning",title:"Acting School",lead:"Develop your craft through practice, performance, and collaboration.",classes:[{title:"Acting",text:"Explore voice, movement, presence, and character."},{title:"Performance",text:"Work with scripts, scenes, rehearsal, and performance."},{title:"Workshops",text:"Join focused sessions designed around specific skills."}],button:"Ask about classes"},
contact:{eyebrow:"Let's connect",title:"Make something with us.",lead:"For bookings, performances, classes, collaborations, and general inquiries.",email:"hello@artistplayground.example",cards:[{label:"Email",value:"hello@artistplayground.example",href:"mailto:hello@artistplayground.example"},{label:"Phone",value:"+63 000 000 0000",href:"tel:+630000000000"},{label:"Location",value:"Philippines"},{label:"Facebook",value:"facebook.com/artistplayground",href:"https://facebook.com/artistplayground"}],topics:["Production","School program","Acting school","Collaboration","General inquiry"]}};